### ISSUE TITLE
Add a back button in mockup editor

### ISSUE THREAD

**Issue by josematiasrivero** [josematiasrivero/mockupdd#12]
![image](https://cloud.githubusercontent.com/assets/753602/19535578/a4176ff6-961e-11e6-957a-28606f5a7ac1.png)

**Comment by MartinAparicioPons** [comment]
I believe this is a strange decision in UX design. This button is not needed, since the browser has a built in back button. Anyway, it's your call @josematiasrivero

**Comment by josematiasrivero** [comment]
Yes, I know that, but it will work as a "save" button for the new user if he/she didn't noticed that the mockup is autosaved. In fact, it can just  run `history.back()` :)
