### ISSUE TITLE
Fix icons for widgets

### ISSUE THREAD

**Issue by josematiasrivero** [josematiasrivero/mockupdd#14]
![image](https://cloud.githubusercontent.com/assets/753602/19535733/513619c6-961f-11e6-9f95-2055e35bf498.png)

**Comment by facug91** [comment]
85a14542b83556e386375583a5667770f5c7c92f
cf2bd6b0b3c450c7c4d039adbf08b228ea32c347
ea40fe02c6bf9aec6246dde84e6dfa98df529bf5
21b48341101973a33bff87d1f45da93d541db60e
